### ISSUE TITLE
The problem of switching from wallet.callisto to explorer.

### ISSUE THREAD

**Issue by gponic** [EthereumCommonwealth/CommunityRequests#10]
https://wallet.callisto.network/
The error has not been corrected for quite a long time, more than six months, although we have written about this error more than once.
It was indicated that there would be a new explorer and this is not a priority right now.

In the section:
Transaction History
CLO(https://explorer.callisto.network)

Invalid address:
https://explorer.callisto.network/addr/0x......

Must be:
https://explorer.callisto.network/address/0x......

The problem, as stated in the community:
Duplication of the response.
Access-Control-Allow-Origin', '*'

**Comment by 11FaTuSh11** [comment]
This problem has long been known.
The developer replied that it makes no sense to fix this code (**wallet**), because the **new wallet**, which has been developed over a long time will soon be available for all.
So I doubt that it will be corrected because it _**costs human resources and money**_

**Comment by DzikNsk** [comment]
What about adding "/addr/*"-> "/address/*" redirects to explorer? this is a quick solution via .htaccess and can be a solution for this old annoying bug. Even if new wallet will be released in a few weeks.

**Comment by 11FaTuSh11** [comment]
Yes, I agree with you, for us as users it is easy to perform even as you pointed out through `.htaccess`, but not for a commercial company...
Kind of like bureaucracy, but it's commerce, I think you get the point.

**Comment by 11FaTuSh11** [comment]
A new wallet has just appeared, still in beta, but it is available
https://hub.callisto.network/

**Comment by Dexaran** [comment]
Move the discussion here https://github.com/EthereumCommonwealth/CommunityRequests/issues/14
