### ISSUE TITLE
Problem with correct conversion display ccETH ERC20 on soy.finance exchange

### ISSUE THREAD

**Issue by gponic** [EthereumCommonwealth/CommunityRequests#3]
Problem with correct conversion display ccETH ERC20 on soy.finance exchange
<img width="319" alt="Screenshot_490" src="https://user-images.githubusercontent.com/123863044/217431789-0d2e0803-bbd5-4f77-adbd-bc54a45b0b66.png">

**Comment by YaStaer** [comment]
It's not conversion display problem. It's old ERC20 cc ETH token.
ccETH ERC20 and ccBNB ERC20 need to remove from 'swap' tab so as not to mislead users.

**Comment by MufCZ** [comment]
Old ERC20 version of ETH and BNB are removed
