### ISSUE TITLE
It is advisable to add active nodes to the chainlist to solve the problem in work Metamask

### ISSUE THREAD

**Issue by gponic** [EthereumCommonwealth/CommunityRequests#4]
Sometimes there are problems connecting Metamask
https://chainlist.org/?search=clo
<img width="493" alt="Screenshot_489" src="https://user-images.githubusercontent.com/123863044/217432533-2e5594e5-875c-40ec-918c-9cc94417f203.png">

**Comment by MufCZ** [comment]
https://rpc.callisto.network is not one server.
Instances of our RPC servers have this url

**Comment by gponic** [comment]
> https://rpc.callisto.network is not one server. Instances of our RPC servers have this url

This is more of a recommendation, because when there are problems interacting with nodes in Metamask, you can write another one and check on of https://chainlist.org/?search=clo

**Comment by gponic** [comment]
Here is an example of displaying RPC servers on ETH, ETC
This adds solidity and network resiliency.
<img width="879" alt="Screenshot_524" src="https://user-images.githubusercontent.com/123863044/219553632-5730b126-c11a-439b-8cb6-d540ea7d07ec.png">
<img width="883" alt="Screenshot_525" src="https://user-images.githubusercontent.com/123863044/219553641-f69d2452-8d1b-431c-a717-467c3da3edc9.png">
