### ISSUE TITLE
date format on and icons on https://audits.callisto.network/

### ISSUE THREAD

**Issue by YaStaer** [EthereumCommonwealth/CommunityRequests#7]
1) icons
![image](https://user-images.githubusercontent.com/124512503/217905310-60df0ec3-bf35-4b1a-8ac3-f95984175327.png)
![image](https://user-images.githubusercontent.com/124512503/217906738-e0fcf12b-2152-48ea-9639-d0b2acadb61d.png)
and more others

2) chaos in audit dates
![image](https://user-images.githubusercontent.com/124512503/217905645-53ce3962-fa26-44ea-afe2-a6abeb5f4d6c.png)
![image](https://user-images.githubusercontent.com/124512503/217905798-67bb67f9-a793-4ab5-ab52-9319024782d4.png)

3) bring dates to a common form "mm/dd/yyyy" or "dd/mm/yyyy", and not like this "m/dd/yyyy" or "mm/d/yyyy"

4) this buttons link to main page callisto.network
![image](https://user-images.githubusercontent.com/124512503/217907403-2380385c-a2a2-4285-ab0e-c7e09e425ce5.png)

**Comment by MufCZ** [comment]
@dragnoir could you pls check?

**Comment by YaStaer** [comment]
no changes for links and dates
![image](https://user-images.githubusercontent.com/124512503/218813086-0bb236ef-0902-4cfa-aacf-37659a0b6c47.png)
![image](https://user-images.githubusercontent.com/124512503/218813199-98a093dc-14a1-4ff5-9e97-011136a003c8.png)
![image](https://user-images.githubusercontent.com/124512503/218813294-182c492e-3e1d-4c1c-8fa1-8cc2e835118a.png)

**Comment by 11FaTuSh11** [comment]
> @dragnoir could you pls check?

OMG! pls check ETHplode (ETHPLO) 
![image](https://user-images.githubusercontent.com/73724555/218980494-a26d3dce-a2c0-4a85-a21b-60b1eb2c81d9.png)

**Comment by gponic** [comment]
> @dragnoir could you pls check?

<img width="927" alt="Screenshot_526" src="https://user-images.githubusercontent.com/123863044/219555238-d24b8014-43b7-41ee-9543-928714cba13e.png">

**Comment by Dexaran** [comment]
cc @MufCZ @yuriy77k

**Comment by dragnoir** [comment]
I can work on this later.

**Comment by YaStaer** [comment]
Are you seriously? Did you find time to add new audits, but not fix the jambs?

**Comment by Dexaran** [comment]
This issue seems to be solved, right?

@dragnoir @YaStaer

**Comment by 11FaTuSh11** [comment]
It's like they can't hear me, or they just ignore me. The post creator said to do either day/month/year or month/day/year. 
I have already pointed out this error several times! Check position 254!
It's as if those who fix the errors don't see them when you point them out.
Look at my screenshots above and you will see the shameful progression in question. 
@dragnoir @Dexaran @YaStaer
![image](https://user-images.githubusercontent.com/73724555/224133279-e1ee1ff0-a06b-499f-a2bf-26f2938d816d.png)

**Comment by YaStaer** [comment]
point 3. if the artist sees it that way, then why not.
point 4. I would still correct the copyright and links. for example like this

![image](https://user-images.githubusercontent.com/124512503/224218850-b87e1bdf-a31b-46b9-a914-acf2be05470a.png)

**Comment by Dexaran** [comment]
> It's like they can't hear me, or they just ignore me. The post creator said to do either day/month/year or month/day/year. I have already pointed out this error several times! Check position 254! It's as if those who fix the errors don't see them when you point them out. Look at my screenshots above and you will see the shameful progression in question. @dragnoir @Dexaran @YaStaer ![image](https://user-images.githubusercontent.com/73724555/224133279-e1ee1ff0-a06b-499f-a2bf-26f2938d816d.png)

I don't see this issue anymore. Probably you need to clear cache 

![AuditsCallistoNetwork](https://user-images.githubusercontent.com/26142412/224337232-71f0516a-7295-4158-828e-3dc312272124.png)

**Comment by Dexaran** [comment]
> point 3. if the artist sees it that way, then why not. point 4. I would still correct the copyright and links. for example like this
> 
> ![image](https://user-images.githubusercontent.com/124512503/224218850-b87e1bdf-a31b-46b9-a914-acf2be05470a.png)

I also don't see "Main page Callisto" but the links point to callito.network/

COPYRIGHT 2022 is still there though

**Comment by Dexaran** [comment]
I am closing this thread as all the reported issues are resolved.
Feel free to open a new one if you find any inconsistency and thank you for your feedback.

@YaStaer you can provide your hex-address if you are willing to accept a small tip for opening the issue and reporting real issues that were fixed.

**Comment by YaStaer** [comment]
Ok. Thanks!
0xBA39e0d29296d0858fAFDbd2eC4F7e5efD6aee5B

**Comment by Dexaran** [comment]
https://explorer.callisto.network/tx/0xef11c47584dd26bf9e5a9d1edd38fca8d57ec13472d5b6e57ac2bcc10c6f74b3
