### ISSUE TITLE
The problem of claim transaction, in the receiving network.

### ISSUE THREAD

**Issue by gponic** [EthereumCommonwealth/CommunityRequests#9]
Сreated with Upaut.
Meta mask calculates the amount of gas based on the function being called.
If the gas cost is low, metamask cannot brand the transaction. (lack of gas limit)
It is necessary to manually adjust the gas limit when signing a transaction in meta mask.
This can be corrected without relying on the meta mask gas calculation, but by setting a gas limit when generating a transaction with excess.
Fewer transactions will be included in the current block, meta mask will calculate the gas consumption of approximately 98% of the gas limit

**Comment by MufCZ** [comment]
We have fixed both claim and claim previous transaction to estimate gas in code without metamask and increase by 20 000 for safety margin. 
Thanks, solved!

**Comment by gponic** [comment]
> We have fixed both claim and claim previous transaction to estimate gas in code without metamask and increase by 20 000 for safety margin. Thanks, solved!

I think the gas limit should be about 120,000 gas accepted, previously ETH was spent on a transaction in the receiving network, otherwise the transaction will not pass.
Gas Limit & Usage by Txn: 150,000 | 94,811 (63.21%)
Gas Fees: Base: 44.869960452 Gwei |Max: 47 Gwei
